
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rhsystem
      POSTGRES_PASSWORD: Rhsyst3m
      POSTGRES_DB: rhsystem
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: